# Generated by Django 4.2 on 2023-04-18 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_blog_sub_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subcategory',
            field=models.ForeignKey(default=None, limit_choices_to={'category__id': django.db.models.expressions.OuterRef('category_id')}, on_delete=django.db.models.deletion.CASCADE, to='root.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(limit_choices_to={'subcategories__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='root.category'),
        ),
    ]
