# Generated by Django 4.2 on 2023-04-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_blog_subcategory_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10),
        ),
    ]
