# Generated by Django 4.2 on 2023-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_alter_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='root.tag'),
        ),
    ]
