# Generated by Django 4.2 on 2023-04-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_tag_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='overview',
            field=models.TextField(default='There is nothing to show', max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='root.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.category'),
        ),
    ]
