# Generated by Django 4.1.5 on 2023-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_Name',
            field=models.CharField(max_length=1000),
        ),
    ]
