# Generated by Django 4.1.5 on 2023-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_task_deleteid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deleteID',
            field=models.TextField(max_length=10000000, unique=True),
        ),
    ]
