# Generated by Django 4.1.5 on 2023-03-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_task_deleteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deleteID',
            field=models.TextField(max_length=10000000),
        ),
    ]
