# Generated by Django 4.1.5 on 2023-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_alter_task_deleteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateAndTimeToCompleteParticularTask',
            field=models.DateTimeField(),
        ),
    ]
