# Generated by Django 4.1.5 on 2023-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_remove_task_date_remove_task_time_task_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(max_length=200),
        ),
    ]
